### PR TITLE
fix: ignore MaxFlushDelay for blocking commands

### LINKED ISSUE #379: Blocking commands should ignore ClientOption.MaxFlushDelay
Blocking commands are executed in dedicated client which is aquired from pool.
So, there is no sense to wait other commands to be written.

### PR DESCRIPTION
**Pull request by unknowntpo**
We check if one or multi has block command, if true, then there's no need to sleep.

### CODE REVIEW

**Comment by unknowntpo** [comment]
@rueian This test takes too much time, maybe something is wrong.
https://app.circleci.com/pipelines/github/redis/rueidis/1021/workflows/2868a79d-6e02-4b6e-aead-d65fa1c4e01b/jobs/977

**Comment by rueian** [comment]
> @rueian This test takes too much time, maybe something is wrong. https://app.circleci.com/pipelines/github/redis/rueidis/1021/workflows/2868a79d-6e02-4b6e-aead-d65fa1c4e01b/jobs/977

It looks like the DragonflyDB crashed during the test. Now the tests are passed after rerun.

**Comment by unknowntpo** [comment]
> > @rueian This test takes too much time, maybe something is wrong. https://app.circleci.com/pipelines/github/redis/rueidis/1021/workflows/2868a79d-6e02-4b6e-aead-d65fa1c4e01b/jobs/977
> 
> 
> 
> It looks like the DragonflyDB crashed during the test. Now the tests are passed after rerun.

Thanks for helping!
And BTW, I notice that the test for MaxFlushDelay is weird, it init a Waitgroup, but didn't use what.Wait() to wait for it. 
What's the purpose of this test?

https://github.com/redis/rueidis/blob/f10a1ee7c7b42f00469a841ebc79afb3e83342d0/pipe_test.go#L765

**Comment by rueian** [comment]
> > > @rueian This test takes too much time, maybe something is wrong. https://app.circleci.com/pipelines/github/redis/rueidis/1021/workflows/2868a79d-6e02-4b6e-aead-d65fa1c4e01b/jobs/977
> > 
> > 
> > It looks like the DragonflyDB crashed during the test. Now the tests are passed after rerun.
> 
> Thanks for helping! And BTW, I notice that the test for MaxFlushDelay is weird, it inits a WaitGroup, but didn't use wg.Wait() to wait for it. What's the purpose of this test?
> 
> https://github.com/redis/rueidis/blob/f10a1ee7c7b42f00469a841ebc79afb3e83342d0/pipe_test.go#L765

Yes, the `wg` is not used and can be removed.

The purpose of that test is just to make sure that the `mock.Expect("PING").ReplyString("OK")` can be passed.

**Pull request merged**
