### PR TITLE
Replica one of arguments

### PR DESCRIPTION
**Pull request by nirrattner**
It looks like this isn't quite working at the moment, I may have misconfigured the JSON, or else I may have to look into the code generation next week to see exactly what is going on.

### CODE REVIEW

**Comment by rueian** [comment]
Hi @nirrattner, thanks and I am sorry about that.

Could you help change the [`Walk`](https://github.com/redis/rueidis/blob/55961cccac95e929bb3db918ba47767da5fc85d5/hack/cmds/gen.go#L333C1-L343C2) function to this and generate those builders again?

```go
func (n *node) Walk(fn func(node *node)) {
	next := n
	for next != nil {
		if next.Child != nil {
			next.Child.Walk(fn)
		} else {
			fn(next)
			if next.Arg.Type == "oneof" {
				for _, s := range next.GoStructs() {
					for _, ns := range s.NextNodes {
						ns.Walk(fn)
					}
				}
			}
		}
		next = next.Next
	}
}
```

**Comment by rueian** [comment]
Never mind. I have updated it here https://github.com/redis/rueidis/commit/6ecaa43701fb7e7581faf9b10c253b4e9c1e14ef.

Please just rebase and regenerate.

**Comment by nirrattner** [comment]
Hey, sorry for the delay in getting this in, and thank you for doing all of the hard work of implementing and fixing the code generation. Last week was a bit hectic for me

**Comment by rueian** [comment]
Hi @nirrattner, it’s ok. Thank you very much for your contribution!

**Pull request merged**
