### PR TITLE
Upgrade otel package dependencies

### PR DESCRIPTION
**Pull request by VladyslavLukyanenko**

### CODE REVIEW

**Comment by rueian** [comment]
Hi @VladyslavLukyanenko, the `go 1.20` in go.mod files should also be changed to `go 1.21`.

**Comment by VladyslavLukyanenko** [comment]
> Hi @VladyslavLukyanenko, the `go 1.20` in go.mod files should also be changed to `go 1.21`.

Done!

**Comment by VladyslavLukyanenko** [comment]
> Thanks @VladyslavLukyanenko! Are there any otel API changes we should be aware of?

I'm not too sure, but I was unable to run the redis otel package with my other packages, since the schema url was different in here than in my other packages it was throwing merge conflict

**Comment by VladyslavLukyanenko** [comment]
> What schema url are you referring to?

Basically if we have a library that uses an older version of otel, and another library uses a newer one, it tries to merge the schemas

https://github.com/open-telemetry/opentelemetry-go/issues/4476
https://github.com/open-telemetry/opentelemetry-go/issues/4476#issuecomment-1840665173

**Comment by rueian** [comment]
Thanks @VladyslavLukyanenko! A new version will be released this week.

**Pull request merged**
