### PR TITLE
Add FT.ALTER in OM JSON and Hash repo

### LINKED ISSUE #632: how to add new index to old ones
So i have these indexes on the first startup:
```go
	if err := r.Repository.CreateIndex(context.Background(), func(schema om.FtCreateSchema) rueidis.Completed {
		return schema.
			FieldName("$.user.owner").As("owner").Tag().
			FieldName("$.user.name").As("name").Tag().
			Build()
	}); err != nil {
		logs.Warning(err)
	}
```

now I need to add a new index:
```go
	if err := r.Repository.CreateIndex(context.Background(), func(schema om.FtCreateSchema) rueidis.Completed {
		return schema.
			FieldName("$.user.owner").As("owner").Tag().
			FieldName("$.user.name").As("name").Tag().
			FieldName("$.user.id").As("id").Tag().
			Build()
	}); err != nil {
		logs.Warning(err)
	}
```

But I get an index already exists error. I need my Redis to be persistent and can't flush everything.

### PR DESCRIPTION
**Pull request by imvtsl**
Signed-off-by: Vatsal <vatsal.v.anand@gmail.com>

Closes #632.

### CODE REVIEW

**Comment by rueian** [comment]
Hi @imvtsl, are you still working on testing?

**Comment by imvtsl** [comment]
Hey @rueian 
I took a pause after seeing the discussion on the issue. I was just about to ping you regarding this PR, but you beat me to it!

Before I dive back in, I wanted to clarify—are we still good with the solution developed in this PR?
Does [this](https://github.com/redis/rueidis/issues/632#issuecomment-2412628041) impact this PR in any way? Apologies if it's a basic question, I am new to this repository and Redis.

**Comment by rueian** [comment]
The discussion don’t affect this PR. FT.ALTER itself is still a useful feature.

**Comment by imvtsl** [comment]
Thank you for clarification. I will resume right away!

**Comment by imvtsl** [comment]
Hi @rueian 
I have added tests in hash_test and json_test for this feature and have verifed the coverage using dockertest.sh.

Is there any style guide that we reference? If yes, can you share that so I can look it up make any required changes before I update this PR from Draft to Ready for Review.

**Comment by rueian** [comment]
> Is there any style guide that we reference? If yes, can you share that so I can look it up make any required changes before I update this PR from Draft to Ready for Review.

The tests are already looked good to me.



> `alter.Schema().Add().Field("$.Nested.F1").Options("TEXT SORTABLE").Build()` fails with `json_test.go:245: Invalid field type for field '$.Nested.F1\'.` error.

I think that was a bug caused by the wrong command definitions. The `options` should be marked as `"multiple": true`: https://github.com/redis/rueidis/blob/25821d0444e88e344cd27e66d7c9b4f27da7c580/hack/cmds/commands_search.json#L357-L360

I think we can have another PR to fix that.

**Comment by imvtsl** [comment]
Thanks, I marked it as ready for review. I don't see the option to request review. @rueian can you review this PR?

> I think that was a bug caused by the wrong command definitions. The options should be marked as "multiple": true:
> 
> [rueidis/hack/cmds/commands_search.json](https://github.com/redis/rueidis/blob/25821d0444e88e344cd27e66d7c9b4f27da7c580/hack/cmds/commands_search.json#L357-L360)
> 
> Lines 357 to 360 in [25821d0](https://github.com/redis/rueidis/commit/25821d0444e88e344cd27e66d7c9b4f27da7c580)
> 
>  { 
>    "name": "options", 
>    "type": "string" 
>  } 
> I think we can have another PR to fix that.

Can I create the issue and raise PR if it's that small a change?

**Comment by rueian** [comment]
Sure, thanks!

**Comment by imvtsl** [comment]
I created this [issue](https://github.com/redis/rueidis/issues/654) for it. I will raise PR for it as soon as this PR is merged.

**Pull request merged**
