### PR TITLE
[FEAT] minor increase in coverage for adapter.go under rueidiscompat

### PR DESCRIPTION
**Pull request by SoulPancake**
Part of #487 

~This also introduces CFAdd BFAdd~

### CODE REVIEW

**Comment by SoulPancake** [comment]
Wait I guess I modified the generated files
Can you suggest hwo they are generated?
is there a proto? @rueian

**Comment by SoulPancake** [comment]
I think it's from hack/cmds/commands_bloom.json
Can you suggest @rueian

**Comment by SoulPancake** [comment]
I guess I figured it out, please review @rueian

**Comment by rueian** [comment]
Hi @SoulPancake, I don't think we can make bf.add and cf.add cacheable. They are not read-only commands.

**Comment by SoulPancake** [comment]
@rueian Understood, I have updated it, Can you please review it @rueian

**Comment by rueian** [comment]
LGTM. Thanks @SoulPancake!

**Pull request merged**
